package com.chessapp.server.application.dto;

import java.util.List;

public class GameResponseDto {
    private Long gameId;

    // White Player Info
    private String whitePlayer;
    private String whiteDisplayName;
    private int whiteRating;
    private String whiteOpponent;
    private String whiteOpponentDisplayName;
    private int whiteOpponentRating;
    private int whiteWinDelta;
    private int whiteDrawDelta;
    private int whiteLossDelta;

    // Black Player Info
    private String blackPlayer;
    private String blackDisplayName;
    private int blackRating;
    private String blackOpponent;
    private String blackOpponentDisplayName;
    private int blackOpponentRating;
    private int blackWinDelta;
    private int blackDrawDelta;
    private int blackLossDelta;

    private String boardState;
    private List<String> moves;
    private Boolean isWhiteTurn;
    private String timeControl;
    private Integer whiteTimeLeft;
    private Integer blackTimeLeft;
    private String state;
    private String result;

    // Constructor, Getters and Setters can be generated by IDE or Lombok
    // For now, creating a simplified parameterized constructor

    public GameResponseDto() {
    }

    public Long getGameId() {
        return gameId;
    }

    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    public void setWhitePlayer(String whitePlayer) {
        this.whitePlayer = whitePlayer;
    }

    public void setWhiteDisplayName(String whiteDisplayName) {
        this.whiteDisplayName = whiteDisplayName;
    }

    public void setWhiteRating(int whiteRating) {
        this.whiteRating = whiteRating;
    }

    public void setWhiteOpponent(String whiteOpponent) {
        this.whiteOpponent = whiteOpponent;
    }

    public void setWhiteOpponentDisplayName(String whiteOpponentDisplayName) {
        this.whiteOpponentDisplayName = whiteOpponentDisplayName;
    }

    public void setWhiteOpponentRating(int whiteOpponentRating) {
        this.whiteOpponentRating = whiteOpponentRating;
    }

    public void setWhiteWinDelta(int whiteWinDelta) {
        this.whiteWinDelta = whiteWinDelta;
    }

    public void setWhiteDrawDelta(int whiteDrawDelta) {
        this.whiteDrawDelta = whiteDrawDelta;
    }

    public void setWhiteLossDelta(int whiteLossDelta) {
        this.whiteLossDelta = whiteLossDelta;
    }

    public void setBlackPlayer(String blackPlayer) {
        this.blackPlayer = blackPlayer;
    }

    public void setBlackDisplayName(String blackDisplayName) {
        this.blackDisplayName = blackDisplayName;
    }

    public void setBlackRating(int blackRating) {
        this.blackRating = blackRating;
    }

    public void setBlackOpponent(String blackOpponent) {
        this.blackOpponent = blackOpponent;
    }

    public void setBlackOpponentDisplayName(String blackOpponentDisplayName) {
        this.blackOpponentDisplayName = blackOpponentDisplayName;
    }

    public void setBlackOpponentRating(int blackOpponentRating) {
        this.blackOpponentRating = blackOpponentRating;
    }

    public void setBlackWinDelta(int blackWinDelta) {
        this.blackWinDelta = blackWinDelta;
    }

    public void setBlackDrawDelta(int blackDrawDelta) {
        this.blackDrawDelta = blackDrawDelta;
    }

    public void setBlackLossDelta(int blackLossDelta) {
        this.blackLossDelta = blackLossDelta;
    }

    public void setBoardState(String boardState) {
        this.boardState = boardState;
    }

    public void setMoves(List<String> moves) {
        this.moves = moves;
    }

    public void setIsWhiteTurn(Boolean whiteTurn) {
        isWhiteTurn = whiteTurn;
    }

    public void setTimeControl(String timeControl) {
        this.timeControl = timeControl;
    }

    public void setWhiteTimeLeft(Integer whiteTimeLeft) {
        this.whiteTimeLeft = whiteTimeLeft;
    }

    public void setBlackTimeLeft(Integer blackTimeLeft) {
        this.blackTimeLeft = blackTimeLeft;
    }

    public void setState(String state) {
        this.state = state;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getWhiteOpponent() {
        return whiteOpponent;
    }

    public String getWhiteOpponentDisplayName() {
        return whiteOpponentDisplayName;
    }

    public int getWhiteOpponentRating() {
        return whiteOpponentRating;
    }

    public int getWhiteWinDelta() {
        return whiteWinDelta;
    }

    public int getWhiteDrawDelta() {
        return whiteDrawDelta;
    }

    public int getWhiteLossDelta() {
        return whiteLossDelta;
    }

    public String getBlackDisplayName() {
        return blackDisplayName;
    }

    public int getBlackRating() {
        return blackRating;
    }

    public String getBlackOpponent() {
        return blackOpponent;
    }

    public String getBlackOpponentDisplayName() {
        return blackOpponentDisplayName;
    }

    public int getBlackOpponentRating() {
        return blackOpponentRating;
    }

    public int getBlackWinDelta() {
        return blackWinDelta;
    }

    public int getBlackDrawDelta() {
        return blackDrawDelta;
    }

    public int getBlackLossDelta() {
        return blackLossDelta;
    }

    // basic getters...
    public String getWhitePlayer() {
        return whitePlayer;
    }

    public String getWhiteDisplayName() {
        return whiteDisplayName;
    }

    public int getWhiteRating() {
        return whiteRating;
    }

    public String getBlackPlayer() {
        return blackPlayer;
    }

    public String getBoardState() {
        return boardState;
    }

    public List<String> getMoves() {
        return moves;
    }

    public Boolean getIsWhiteTurn() {
        return isWhiteTurn;
    }

    public String getTimeControl() {
        return timeControl;
    }

    public Integer getWhiteTimeLeft() {
        return whiteTimeLeft;
    }

    public Integer getBlackTimeLeft() {
        return blackTimeLeft;
    }

    public String getState() {
        return state;
    }

    public String getResult() {
        return result;
    }
}
